### ISSUE TITLE
TEASConsole stops working propertly

### ISSUE THREAD

**Issue by F-luxus** [TheEpicSnowWolf/TheEpicAudioStreamer#3] opened 2022-04-03 09:07 UTC
Hello, 
Thank you for good tool like TEASConsole. Its helps me alot to stream audio to Discord. But now  I have big problems about this tool. 
Few weeks ago I noticed that this script using all my server RAM (Server have ~120GB) , so TEASConsole.exe ate more than 100GB itself.
I was forced to closed application and run it again. After restarting application ate jus ~50MB, but yesterday its happens again. After force close I can not run this application anymore without these errors: 
`[2022-04-03 12:04:37 +03:00] [101 /Startup     ] [Info ] DSharpPlus, version 4.2
.0-nightly-01045
[2022-04-03 12:04:39 +03:00] [108 /WebSocketRec] [Error] Socket handler suppress
ed an exception
Newtonsoft.Json.JsonSerializationException: Error setting value to 'OAuthFlags'
on 'DSharpPlus.Entities.DiscordMember'.
 ---> System.NullReferenceException: Object reference not set to an instance of
an object.
   at DSharpPlus.Entities.DiscordMember.get_User()
   at DSharpPlus.Entities.DiscordMember.set_OAuthFlags(Nullable1 value)
   at lambda_method308(Closure , Object , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object targ
et, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object targ
et, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValu
e(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract
containerContract, JsonProperty containerProperty, JsonReader reader, Object tar
get)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(
Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty m
ember, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Js
onReader reader, Type objectType, JsonContract contract, JsonProperty member, Js
onContainerContract containerContract, JsonProperty containerMember, Object exis
tingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInte
rnal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem
ber, JsonContainerContract containerContract, JsonProperty containerMember, Obje
ct existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IL
ist list, JsonReader reader, JsonArrayContract contract, JsonProperty containerP
roperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(Json
Reader reader, Type objectType, JsonContract contract, JsonProperty member, Obje
ct existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInte
rnal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem
ber, JsonContainerContract containerContract, JsonProperty containerMember, Obje
ct existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Jso
nReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(Json
Reader reader, Type objectType)
   at DSharpPlus.Net.Serialization.SnowflakeArrayAsDictionaryJsonConverter.ReadJ
son(JsonReader reader, Type objectType, Object existingValue, JsonSerializer ser
ializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConv
ertable(JsonConverter converter, JsonReader reader, Type objectType, Object exis
tingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValu
e(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract
containerContract, JsonProperty containerProperty, JsonReader reader, Object tar
get)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(
Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty m
ember, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Js
onReader reader, Type objectType, JsonContract contract, JsonProperty member, Js
onContainerContract containerContract, JsonProperty containerMember, Object exis
tingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInte
rnal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem
ber, JsonContainerContract containerContract, JsonProperty containerMember, Obje
ct existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Jso
nReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type
 objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectT
ype)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonS
erializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at DSharpPlus.Net.Serialization.DiscordJson.ToDiscordObject[T](JToken token)
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|445_1(IW
ebSocketClient sender, SocketMessageEventArgs e)`
`Discord bot showing this error when using /joinst:
The application did not respond`

My env:
* Windows Server 2012 R2
* Application is running 24/7

**Comment by TheEpicSnowWolf** [comment] 2022-04-03 15:38
Thanks for raising this. This was caused by an issue with DSharpPlus, but is fixed in their new nightly and, consequently, in [TEAS 0.5.2](https://github.com/TheEpicSnowWolf/TheEpicAudioStreamer/releases/tag/v0.5.2).

**Closed by TheEpicSnowWolf** 2022-04-03 15:38 UTC
Labels: bug
